### ISSUE TITLE
Elements get "pulled"

### ISSUE THREAD

**Issue by justingluska** [gmrchk/blobity#11]
Is there any way to fix links from getting pulled/dragged when hovering over them? I can't seem to figure out even turning off magnetic doesn't seem to be working

https://user-images.githubusercontent.com/53244307/176748176-bcf519df-5390-452b-8e56-a1f339b2fc1b.mov

**Comment by gmrchk** [comment]
Can you include your Blobity loading/configuration?

**Comment by justingluska** [comment]
Yup, this is what I have:

<script src="https://cdn.blobity.dev/by.js"></script>
<script>
    const blobity = new Blobity({
        licenseKey: '1B11DFF0-FBFA4F53-8D752D02-B770DAA0'
    });
    blobity.updateOptions({ magnetic: false });
    blobity.updateOptions({ size: 0 });
    blobity.updateOptions({ radius: 10});
    blobity.updateOptions({ dotColor: "#E0CB70" })
</script>


From: Georgy Marchuk ***@***.***>
Reply-To: gmrchk/blobity ***@***.***>
Date: Thursday, June 30, 2022 at 1:15 PM
To: gmrchk/blobity ***@***.***>
Cc: Justin Gluska ***@***.***>, Author ***@***.***>
Subject: Re: [gmrchk/blobity] Elements get "pulled" (Issue #11)


Can you include your Blobity loading/configuration?

**Comment by gmrchk** [comment]
The CDN link you're using to load Blobity includes [something called autostart](https://github.com/gmrchk/blobity#installation), which creates one instance of Blobity with default settings, apart from the one you're creating yourself manually. 
Basically, there are two Blobity instances running on the page, with one having the magnetic option enabled, and the second one being the one created by you with your settings. 

This is a common problem. I have to admit, not the brightest decision I had...

To avoid that, please include the "noAutoStart" parameter in the CDN URL. 

<script src="https://cdn.blobity.dev/by.js?noAutoStart"></script>

**Comment by justingluska** [comment]
No worries! That fixed it for me thank you so much.
