### ISSUE TITLE
BUG: Hero Section Buttons Hiding

### ISSUE THREAD

**Issue by Bawanthathilan** [gmrchk/blobity#14]
**Describe your issue**:

Hiding Hero Section Buttons in Main Website
![image](https://user-images.githubusercontent.com/38850236/179896256-58155652-7fcf-4ea0-a24f-2aec6c3cdabf.png)

**Blobity config or any additional relevant code used**:

**Before creating this issue, did you think of...**:
- [x] Have you checked closed issues for similar/related problems?
- [x] Have you provided all helpful information available?
- [x] Have you considered creating a demo repository, or a link to your running project where the problem is reproducible?

**Comment by gmrchk** [comment]
Hey! Thanks a lot for the report!

Should be fixed by https://github.com/gmrchk/blobity/commit/e7f5e4bb308e338374e41f1e3619403eac2d4845.

The fix should already be visible on the main site.
