### ISSUE TITLE
Is it possible to disable the comet effect when moving?

### ISSUE THREAD

**Issue by P4KM4N** [gmrchk/blobity#16]
First of all, WOW!!! Georgy, this library is awesome! And just found out you are also the creator of Swup 🤯

Is it possible to disable the re-shaping of the circle (morphing into a comet like cursor) when moving?
I'm pretty sure my client won't want that (it's awesome, but I'm doing an architect website, and everything need to be subtle).

Thanks!

**Comment by P4KM4N** [comment]
I tipped you $10 on 21 sept. hoping for an answer. Any help would be appreciate to know **how I can disable inertia/momentum, I want the cursor to stay a circle while moving.**

Thanks!

**Comment by gmrchk** [comment]
Hi! Thank you for your patience, apologies, this has slipped through the cracks for me. 

There is currently no way to disable morphing in the current version, but it should be a simple feature to add. [Here's a PR](https://github.com/gmrchk/blobity/pull/21) that would add a new option to disable this morphing behavior. You can observe how this looks over here on the [test site deploy](https://deploy-preview-21--serene-benz-218f72.netlify.app/).

Please, let me know what you think.

**Comment by P4KM4N** [comment]
Demo seems perfect! Unfortunately I did the cursor myself and it was not as cool as your library! :(
Will definitely use it on upcoming project. Thanks! :)

**Comment by gmrchk** [comment]
Awesome, I'll add the documentation for the option and merge the PR!
