### ISSUE TITLE
BUG: CDN not working

### ISSUE THREAD

**Issue by rachit1601** [gmrchk/blobity#17]
**Describe your issue**:
CDN not working

[https://cdn.blobity.dev/by.js](https://cdn.blobity.dev/by.js)

**Before creating this issue, did you think of...**:
- [*] Have you checked closed issues for similar/related problems?
- [*] Have you provided all helpful information available?

**Comment by gmrchk** [comment]
Actually, seems like the main site stopped working also. It was a wrong domain renewal setup... classic. 🤦‍♂️
Thank you for the heads up, shouldn't happen again.

**Comment by rachit1601** [comment]
Thank you ❤️
